# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd1853bb4a49dfb1ef134663bc50cb2b9907efc8ab0b8396d104d496eb38ecf5b04e2458f9c578c91aa173bb99dcdbcd8a63d854de8595ed4fada8b11ed3ccd2

test:
  secret_key_base: 6b3af8bd83601bda5c850b6efd2b9a3e52691a914eb53983a84db1d87151a5f134d9903bd1decde936793be7f20744a66b4c7a48bed96571e541a2c74d4cbf57

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
